## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [2]:
df = pd.read_excel("csea_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW23CS121,ROHITH RAO,Data Science & GenAI - 3nd Yr - CSE - A,11,7,4,0,64%,Critical,5 more,2026-10-08,0
1,4MW23CS165,SUDHARSHAN BHARGAV JOSHI,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11,0,0%,Critical,33 more,Never,11
2,4MW24CS001,A S ANUPAMA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-08,0
3,4MW24CS002,ABHIJNA SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100%,Safe,✓ Met,2026-10-08,0
4,4MW24CS003,ABHISHEK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50%,Critical,12 more,2026-10-08,0
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS059,KARTHIK B NAYAK,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-05,1
61,4MW24CS060,KAVYA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-08,0
62,4MW25CS400,ANAGHA K Y,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83%,Warning,✓ Met,2026-10-05,1
63,4MW25CS402,ANVITHA B A,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92%,Safe,✓ Met,2026-10-08,0
64,4MW25CS403,M NIRANJAN PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,3,9,0,25%,Critical,24 more,2026-09-07,9

#### Section 1: Data Inspection

In [3]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------
print(df.head(10).to_string())
print("\nShape:", df.shape)
print("\nData types:\n", df.dtypes)

      Roll No              Student Name                                  Subject  Total Classes  Present  Absent  Excused Attendance %    Status Classes Needed (75%) Last Present Date  Consecutive Absences
0  4MW23CS121                ROHITH RAO  Data Science & GenAI - 3nd Yr - CSE - A             11        7       4        0          64%  Critical               5 more        2026-10-08                     0
1  4MW23CS165  SUDHARSHAN BHARGAV JOSHI  Data Science & GenAI - 3nd Yr - CSE - A             11        0      11        0           0%  Critical              33 more             Never                    11
2  4MW24CS001               A S ANUPAMA  Data Science & GenAI - 3nd Yr - CSE - A             12       10       2        0          83%   Warning                ✓ Met        2026-10-08                     0
3  4MW24CS002            ABHIJNA SHETTY  Data Science & GenAI - 3nd Yr - CSE - A             12       12       0        0         100%      Safe                ✓ Met        2026-10-08                     0
4  4MW24CS003                  ABHISHEK  Data Science & GenAI - 3nd Yr - CSE - A             12        6       6        0          50%  Critical              12 more        2026-10-08                     0
5  4MW24CS004          ADITHYA A SALIAN  Data Science & GenAI - 3nd Yr - CSE - A             12       10       2        0          83%   Warning                ✓ Met        2026-10-08                     0
6  4MW24CS005         AKANKSHA G SHETTY  Data Science & GenAI - 3nd Yr - CSE - A             12       10       2        0          83%   Warning                ✓ Met        2026-10-08                     0
7  4MW24CS006            AMULYA B KULAL  Data Science & GenAI - 3nd Yr - CSE - A             12        9       3        0          75%   Warning                ✓ Met        2026-10-08                     0
8  4MW24CS007                    ANANYA  Data Science & GenAI - 3nd Yr - CSE - A             12       12       0        0         100%      Safe                ✓ Met        2026-10-08                     0
9  4MW24CS008                  ANANYA B  Data Science & GenAI - 3nd Yr - CSE - A             12       12       0        0         100%      Safe                ✓ Met        2026-10-08                     0

Shape: (65, 12)

Data types:
 Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [4]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------
print("Missing (NaN) values per column:\n", df.isnull().sum())
never = (df["Last Present Date"] == "Never").sum()
print(f"\nStudents with 'Never' in Last Present Date: {never}")
print("Columns containing null/placeholder values: ['Last Present Date'] (as 'Never')" if never else "No nulls")

Missing (NaN) values per column:
 Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

Students with 'Never' in Last Present Date: 3
Columns containing null/placeholder values: ['Last Present Date'] (as 'Never')

In [5]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------
df.columns = (df.columns.str.strip().str.lower()
              .str.replace(r"[^a-z0-9]+", "_", regex=True).str.strip("_"))
df = df.rename(columns={"attendance": "attendance_pct", "classes_needed_75": "classes_needed_75"})
print(list(df.columns))

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75', 'last_present_date', 'consecutive_absences']

In [6]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------
df["attendance_pct"] = df["attendance_pct"].astype(str).str.replace("%", "", regex=False).astype(float)
df["last_present_date"] = pd.to_datetime(df["last_present_date"], errors="coerce")  # "Never" -> NaT
print(df[["attendance_pct", "last_present_date"]].dtypes)
print("NaT count:", df["last_present_date"].isna().sum())
df.head()

attendance_pct              float64
last_present_date    datetime64[us]
dtype: object
NaT count: 3

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences
0,4MW23CS121,ROHITH RAO,Data Science & GenAI - 3nd Yr - CSE - A,11,7,4,0,64.0,Critical,5 more,2026-10-08,0
1,4MW23CS165,SUDHARSHAN BHARGAV JOSHI,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11,0,0.0,Critical,33 more,NaT,11
2,4MW24CS001,A S ANUPAMA,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0,83.0,Warning,✓ Met,2026-10-08,0
3,4MW24CS002,ABHIJNA SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0
4,4MW24CS003,ABHISHEK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50.0,Critical,12 more,2026-10-08,0

#### Section 2: Filtering & Selection

In [7]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
critical = df[df["status"] == "Critical"].sort_values("attendance_pct", ascending=True)
critical

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences
1,4MW23CS165,SUDHARSHAN BHARGAV JOSHI,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11,0,0.0,Critical,33 more,NaT,11
21,4MW24CS020,ARON OWEN D'SOUZA,Data Science & GenAI - 3nd Yr - CSE - A,12,0,12,0,0.0,Critical,36 more,NaT,12
51,4MW24CS050,GAUTHAM G PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,0,12,0,0.0,Critical,36 more,NaT,12
35,4MW24CS034,DARREN DSOUZA,Data Science & GenAI - 3nd Yr - CSE - A,12,1,11,0,8.0,Critical,32 more,2026-08-31,11
59,4MW24CS058,JEETHAN WELROY FERNANDES,Data Science & GenAI - 3nd Yr - CSE - A,12,1,11,0,8.0,Critical,32 more,2026-08-31,11
42,4MW24CS041,DHIKSHITH AITHAL KG,Data Science & GenAI - 3nd Yr - CSE - A,12,2,10,0,17.0,Critical,28 more,2026-09-07,9
47,4MW24CS046,DRUSHYA K SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,2,10,0,17.0,Critical,28 more,2026-10-08,0
64,4MW25CS403,M NIRANJAN PRABHU,Data Science & GenAI - 3nd Yr - CSE - A,12,3,9,0,25.0,Critical,24 more,2026-09-07,9
20,4MW24CS019,ANVESH N ACHARYA,Data Science & GenAI - 3nd Yr - CSE - A,12,5,7,0,42.0,Critical,16 more,2026-09-21,6
57,4MW24CS056,HIMESH PRAKASH NAIK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50.0,Critical,12 more,2026-09-28,3
4,4MW24CS003,ABHISHEK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50.0,Critical,12 more,2026-10-08,0
22,4MW24CS021,ARUNA,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50.0,Critical,12 more,2026-10-05,1
58,4MW24CS057,JATIN NAGESH NAIK,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0,50.0,Critical,12 more,2026-10-05,1
55,4MW24CS054,HARSHA S RAO,Data Science & GenAI - 3nd Yr - CSE - A,12,7,5,0,58.0,Critical,8 more,2026-10-08,0
52,4MW24CS051,GOWRISH M SHEREGARA,Data Science & GenAI - 3nd Yr - CSE - A,12,7,5,0,58.0,Critical,8 more,2026-10-08,0
38,4MW24CS037,DEVADIGA SUHAS SURESH,Data Science & GenAI - 3nd Yr - CSE - A,12,7,5,0,58.0,Critical,8 more,2026-10-08,0
0,4MW23CS121,ROHITH RAO,Data Science & GenAI - 3nd Yr - CSE - A,11,7,4,0,64.0,Critical,5 more,2026-10-08,0
27,4MW24CS026,ATHMIK Y ACHARYA,Data Science & GenAI - 3nd Yr - CSE - A,12,8,4,0,67.0,Critical,4 more,2026-10-05,1
49,4MW24CS048,GANAVI SUSHMA,Data Science & GenAI - 3nd Yr - CSE - A,12,8,4,0,67.0,Critical,4 more,2026-10-08,0

In [8]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
df.loc[df["present"] == 0, ["roll_no", "student_name", "consecutive_absences"]]

       roll_no              student_name  consecutive_absences
1   4MW23CS165  SUDHARSHAN BHARGAV JOSHI                    11
21  4MW24CS020         ARON OWEN D'SOUZA                    12
51  4MW24CS050          GAUTHAM G PRABHU                    12

In [9]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
# (a) All Safe students using .loc
safe = df.loc[df["status"] == "Safe"]
display(safe)
# (b) First 15 rows, columns 2-6 using .iloc (columns at positions 2..6)
df.iloc[:15, 2:7]

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences
3,4MW24CS002,ABHIJNA SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0
8,4MW24CS007,ANANYA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0
9,4MW24CS008,ANANYA B,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0
12,4MW24CS011,ANANYA Y BANGERA,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0
14,4MW24CS013,ANKITHA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0
15,4MW24CS014,ANULEKHA NAIK,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0
18,4MW24CS017,ANUSHREE K,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0
23,4MW24CS022,ARYA ASWEEN DESAI,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0
25,4MW24CS024,ASHISH,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0
26,4MW24CS025,ASHRAYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0
28,4MW24CS027,AVISHA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0
30,4MW24CS029,BHOOMIKA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0
31,4MW24CS030,CHANDANA,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0
33,4MW24CS032,CLEONIE,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0
36,4MW24CS035,DEEKSHITH,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0
41,4MW24CS040,DHANYATHA S MADDODI,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0
44,4MW24CS043,DISHA (PRAKASH BANGERA),Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0
48,4MW24CS047,GANAPATHI MALLYA,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0,100.0,Safe,✓ Met,2026-10-08,0
56,4MW24CS055,HIMANI,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0
63,4MW25CS402,ANVITHA B A,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0,92.0,Safe,✓ Met,2026-10-08,0

,subject,total_classes,present,absent,excused
0,Data Science & GenAI - 3nd Yr - CSE - A,11,7,4,0
1,Data Science & GenAI - 3nd Yr - CSE - A,11,0,11,0
2,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0
3,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0
4,Data Science & GenAI - 3nd Yr - CSE - A,12,6,6,0
5,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0
6,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0
7,Data Science & GenAI - 3nd Yr - CSE - A,12,9,3,0
8,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0
9,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0
10,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0
11,Data Science & GenAI - 3nd Yr - CSE - A,12,10,2,0
12,Data Science & GenAI - 3nd Yr - CSE - A,12,11,1,0
13,Data Science & GenAI - 3nd Yr - CSE - A,12,9,3,0
14,Data Science & GenAI - 3nd Yr - CSE - A,12,12,0,0

In [10]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------
df.loc[df["consecutive_absences"] >= 5, ["student_name", "status", "last_present_date"]]

                student_name    status last_present_date
1   SUDHARSHAN BHARGAV JOSHI  Critical               NaT
20          ANVESH N ACHARYA  Critical        2026-09-21
21         ARON OWEN D'SOUZA  Critical               NaT
35             DARREN DSOUZA  Critical        2026-08-31
42       DHIKSHITH AITHAL KG  Critical        2026-09-07
51          GAUTHAM G PRABHU  Critical               NaT
59  JEETHAN WELROY FERNANDES  Critical        2026-08-31
64         M NIRANJAN PRABHU  Critical        2026-09-07

### Section 3: Grouping & Aggregation

In [11]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
status_summary = df.groupby("status").agg(
    student_count=("roll_no", "count"),
    avg_attendance_pct=("attendance_pct", "mean"),
    max_consecutive_absences=("consecutive_absences", "max"),
).round(2)
status_summary

          student_count  avg_attendance_pct  max_consecutive_absences
status
Critical             19               36.26                        12
Safe                 20               96.00                         0
Warning              26               80.50                         1

In [12]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------
df["attendance_category"] = np.select(
    [df["attendance_pct"] >= 90, df["attendance_pct"] >= 75, df["attendance_pct"] >= 60],
    ["Excellent", "Good", "Average"], default="Poor")
df.groupby("attendance_category")["roll_no"].count().rename("students")

attendance_category
Average       3
Excellent    20
Good         26
Poor         16
Name: students, dtype: int64

In [13]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------
totals = df[["total_classes", "present", "absent"]].agg("sum")
print(totals)
# Per-column view using .agg()
df.agg({"total_classes": "sum", "present": "sum", "absent": "sum"})

total_classes    777
present          563
absent           214
dtype: int64

total_classes    777
present          563
absent           214
dtype: int64

In [14]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------
q12 = df.groupby("status").agg(
    present_min=("present", "min"),
    present_max=("present", "max"),
    present_mean=("present", "mean"),
    absent_sum=("absent", "sum"),
).round(2)
q12

          present_min  present_max  present_mean  absent_sum
status
Critical            0            8          4.32         144
Safe               11           12         11.50          10
Warning             9           10          9.65          60

### Section 4: Feature Engineering & Transformation

In [15]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------
df["risk_score"] = df["absent"] * 0.4 + df["consecutive_absences"] * 0.6
top10_risk = df.sort_values("risk_score", ascending=False).head(10)
top10_risk[["roll_no", "student_name", "absent", "consecutive_absences", "risk_score"]]

,roll_no,student_name,absent,consecutive_absences,risk_score
21,4MW24CS020,ARON OWEN D'SOUZA,12,12,12.0
51,4MW24CS050,GAUTHAM G PRABHU,12,12,12.0
59,4MW24CS058,JEETHAN WELROY FERNANDES,11,11,11.0
35,4MW24CS034,DARREN DSOUZA,11,11,11.0
1,4MW23CS165,SUDHARSHAN BHARGAV JOSHI,11,11,11.0
42,4MW24CS041,DHIKSHITH AITHAL KG,10,9,9.4
64,4MW25CS403,M NIRANJAN PRABHU,9,9,9.0
20,4MW24CS019,ANVESH N ACHARYA,7,6,6.4
57,4MW24CS056,HIMESH PRAKASH NAIK,6,3,4.2
47,4MW24CS046,DRUSHYA K SHETTY,10,0,4.0

In [16]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------
df["classes_needed_num"] = (df["classes_needed_75"].str.extract(r"(\d+)")[0]
                            .fillna(0).astype(int))   # "✓ Met" -> 0
df[["student_name", "classes_needed_75", "classes_needed_num"]].head(15)

                     student_name classes_needed_75  classes_needed_num
0                      ROHITH RAO            5 more                   5
1        SUDHARSHAN BHARGAV JOSHI           33 more                  33
2                     A S ANUPAMA             ✓ Met                   0
3                  ABHIJNA SHETTY             ✓ Met                   0
4                        ABHISHEK           12 more                  12
5                ADITHYA A SALIAN             ✓ Met                   0
6               AKANKSHA G SHETTY             ✓ Met                   0
7                  AMULYA B KULAL             ✓ Met                   0
8                          ANANYA             ✓ Met                   0
9                        ANANYA B             ✓ Met                   0
10     ANANYA NAYAK (UMESH NAYAK)             ✓ Met                   0
11  ANANYA NAYAK(VEERENDRA KUMAR)             ✓ Met                   0
12               ANANYA Y BANGERA             ✓ Met                   0
13                 ANEESH ACHARYA             ✓ Met                   0
14                        ANKITHA             ✓ Met                   0

In [17]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------
df["attendance_flag"] = df["attendance_pct"].apply(lambda x: "Defaulter" if x < 75 else "Safe")
df["attendance_flag"].value_counts()

attendance_flag
Safe         46
Defaulter    19
Name: count, dtype: int64

In [18]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------
df["attendance_bin"] = pd.cut(df["attendance_pct"], bins=[0, 50, 75, 90, 100],
                              labels=["Critical", "Warning", "Good", "Excellent"], include_lowest=True)
print(df["attendance_bin"].value_counts().sort_index())
df[["student_name", "attendance_pct", "attendance_bin"]].head(10)

attendance_bin
Critical     13
Warning      14
Good         18
Excellent    20
Name: count, dtype: int64

               student_name  attendance_pct attendance_bin
0                ROHITH RAO            64.0        Warning
1  SUDHARSHAN BHARGAV JOSHI             0.0       Critical
2               A S ANUPAMA            83.0           Good
3            ABHIJNA SHETTY           100.0      Excellent
4                  ABHISHEK            50.0       Critical
5          ADITHYA A SALIAN            83.0           Good
6         AKANKSHA G SHETTY            83.0           Good
7            AMULYA B KULAL            75.0        Warning
8                    ANANYA           100.0      Excellent
9                  ANANYA B           100.0      Excellent

### Section 5: Advanced Analysis

In [19]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------
pd.pivot_table(df, index="status", columns="attendance_category",
               values="roll_no", aggfunc="count", fill_value=0)

attendance_category  Average  Excellent  Good  Poor
status
Critical                   3          0     0    16
Safe                       0         20     0     0
Warning                    0          0    26     0

In [20]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------
# Base name = first word of the name (ignores initials, surnames and bracketed parent names)
df["base_name"] = df["student_name"].str.replace(r"\(.*?\)", "", regex=True).str.strip().str.split().str[0]
dups = df[df["base_name"].duplicated(keep=False)].sort_values(["base_name", "roll_no"])
dups[["roll_no", "student_name", "base_name"]]

       roll_no                   student_name base_name
8   4MW24CS007                         ANANYA    ANANYA
9   4MW24CS008                       ANANYA B    ANANYA
10  4MW24CS009     ANANYA NAYAK (UMESH NAYAK)    ANANYA
11  4MW24CS010  ANANYA NAYAK(VEERENDRA KUMAR)    ANANYA
12  4MW24CS011               ANANYA Y BANGERA    ANANYA
16  4MW24CS015                         ANUSHA    ANUSHA
17  4MW24CS016                  ANUSHA S BHAT    ANUSHA
18  4MW24CS017                     ANUSHREE K  ANUSHREE
19  4MW24CS018              ANUSHREE P TANTRY  ANUSHREE
44  4MW24CS043        DISHA (PRAKASH BANGERA)     DISHA
45  4MW24CS044                 DISHA (UDAY G)     DISHA
46  4MW24CS045                DISHA S POOJARY     DISHA
50  4MW24CS049                    GAUTHAM B K   GAUTHAM
51  4MW24CS050               GAUTHAM G PRABHU   GAUTHAM

In [21]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------
# Hypothetical Student_Details DataFrame (built from the roll numbers, with a few extras that will not match)
student_details = pd.DataFrame({
    "roll_no": df["roll_no"].tolist() + ["4MW23CS999", "4MW24CS999"],
    "branch": "CSE",
    "semester": 5,
})
merged = df.merge(student_details, on="roll_no", how="inner")
print("Merged shape:", merged.shape)
merged[["roll_no", "student_name", "branch", "semester", "attendance_pct", "status"]].head(15)

Merged shape: (65, 20)

,roll_no,student_name,branch,semester,attendance_pct,status
0,4MW23CS121,ROHITH RAO,CSE,5,64.0,Critical
1,4MW23CS165,SUDHARSHAN BHARGAV JOSHI,CSE,5,0.0,Critical
2,4MW24CS001,A S ANUPAMA,CSE,5,83.0,Warning
3,4MW24CS002,ABHIJNA SHETTY,CSE,5,100.0,Safe
4,4MW24CS003,ABHISHEK,CSE,5,50.0,Critical
5,4MW24CS004,ADITHYA A SALIAN,CSE,5,83.0,Warning
6,4MW24CS005,AKANKSHA G SHETTY,CSE,5,83.0,Warning
7,4MW24CS006,AMULYA B KULAL,CSE,5,75.0,Warning
8,4MW24CS007,ANANYA,CSE,5,100.0,Safe
9,4MW24CS008,ANANYA B,CSE,5,100.0,Safe
10,4MW24CS009,ANANYA NAYAK (UMESH NAYAK),CSE,5,83.0,Warning
11,4MW24CS010,ANANYA NAYAK(VEERENDRA KUMAR),CSE,5,83.0,Warning
12,4MW24CS011,ANANYA Y BANGERA,CSE,5,92.0,Safe
13,4MW24CS012,ANEESH ACHARYA,CSE,5,75.0,Warning
14,4MW24CS013,ANKITHA,CSE,5,100.0,Safe

In [22]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------
critical.to_csv("critical_students.csv", index=False)
status_stats = df.groupby("status")[["total_classes", "present", "absent", "attendance_pct", "consecutive_absences", "risk_score"]].describe()
status_stats.to_csv("summary_by_status.csv")
top10_risk.to_csv("top10_risk_score.csv", index=False)
print("Exported: critical_students.csv, summary_by_status.csv, top10_risk_score.csv")

Exported: critical_students.csv, summary_by_status.csv, top10_risk_score.csv